In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
cd /content/drive/MyDrive/Machine learning 2024/Notebooks - Machine Learning/Generic Projects/remove brackets

/content/drive/MyDrive/Machine learning 2024/Notebooks - Machine Learning/Generic Projects/remove brackets

In [ ]:
import pandas as pd

data = pd.read_csv('dataset.csv', names=['x1', 'x2', 'x3', 'y'])
data.head()

       x1    x2  x3  y
0  [-1441 -2228  8]  1
1  [-1727  -769  7]  1
2    -440  2448   8  1
3   -1944  1874  11  2
4    -763 -1235   7  1

In [ ]:
data.dtypes

x1    object
x2     int64
x3    object
y      int64
dtype: object

In [ ]:
data_numeric = data.copy()
data_numeric['x1'] = data['x1'].str.replace('[', '', regex=False).astype('int64')
data_numeric['x3'] = data['x3'].str.replace(']', '', regex=False).astype('int64')
data_numeric.head()

     x1    x2  x3  y
0 -1441 -2228   8  1
1 -1727  -769   7  1
2  -440  2448   8  1
3 -1944  1874  11  2
4  -763 -1235   7  1

In [ ]:
data_numeric.dtypes

x1    int64
x2    int64
x3    int64
y     int64
dtype: object

In [ ]:
X=data_numeric.iloc[:,:-1]
y=data_numeric.iloc[:,-1]

In [ ]:
# Scaling , splitting modeling for all ML algorithms

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Splitting
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Modeling
models = {
    "Logistic Regression": LogisticRegression(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Support Vector Machine": SVC(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name}: Accuracy = {accuracy:.2f}")

Logistic Regression: Accuracy = 0.69
K-Nearest Neighbors: Accuracy = 0.74
Support Vector Machine: Accuracy = 0.76
Decision Tree: Accuracy = 0.75
Random Forest: Accuracy = 0.75